# Generated by Django 5.0.4 on 2024-05-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emaiconfirmation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmaiConfirmation',
            new_name='EmailConfirmation',
        ),
    ]
