# Generated by Django 5.0.4 on 2024-04-20 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_review_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='movies_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True),
        ),
    ]
